spring:
    application:
        name: medication-service
    security:
        user: 
            name: admin
            password: admin 
    boot:
        admin:
            client:
                url: http://localhost:9090
                username: admin
                password: admin
                instance:
                    metadata:
                        user.name: admin
                        user.password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true